### PR TITLE
fix(client) resolve FQDNs ending in dots

### PR DESCRIPTION
**Pull request by locao**

### CODE REVIEW

**Comment by Tieske** [comment]
what are the semantics of a name ending with a dot? are they to be treated as fqdn names? so no domain searches etc?

**Comment by locao** [comment]
Yes, the dot at the end means the name is unambiguous, there's nothing else to search.

**Review by kikito — APPROVED** [review]

**Review by Tieske — CHANGES_REQUESTED** [review]
This doesn't look like it is complete. If the trailing `.` denotes a FQDN, then the iterator (iterating over all the search domains) should be updated/bypassed in that case.

**Comment by Tieske** [comment]
I created an alternative in #122

**Comment by locao** [comment]
Superseded by #122

**Pull request closed without merging**
