### PR TITLE
fix(hosts) ensure hostsfile ipv6 are also normalized with brackets

### PR DESCRIPTION
**Pull request by Tieske**
Additionally relaxes parsing to also allow for port numbers (in
custom hosts files). The DNS client will insert those entries
as SRV records in its cache (other entries will be A or AAAA
type records)

### CODE REVIEW

**Comment by hishamhm** [comment]
> The DNS client will insert those entries as SRV records in its cache (other entries will be A or AAAA type records)

Is this standard behavior? (are ports allowed in the specification of /etc/hosts?)

**Comment by Tieske** [comment]
no, it is not standard. And a `/etc/hosts` file should not include them. But the DNS client allows you to specify another file to parse as the hosts file. And if you choose to do so, then that file can support port numbers this way.

fwiw I also still have doubts on this one.

**Comment by hishamhm** [comment]
I wouldn't add incompatible extensions like that. The part about accepting IPv6 brackets in entries should definitely be in, though.

**Comment by Tieske** [comment]
@hisham reverted the port thing, now only parses IPv6 with brackets

**Pull request merged**
